[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py_cli"
version = "0.6.1"
description = "Missing file utilities"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Lief Koepsel", email = "lkoepsel@wellys.com" }
]
keywords = ["Python", "missing files"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Communications",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12"
]
dependencies = ["click>=8.0", "xxhash"]
urls = { "Homepage" = "https://github.com/lkoepsel/py_cli" }

[project.scripts]
mf = "py_cli.cli:mf"
mfs = "py_cli.cli:mfs"
hw = "py_cli.cli:hw"
ch = "py_cli.cli:ch"
fhc = "py_cli.cli:fhc"

[tool.setuptools]
packages = ["py_cli"]
